language: go

addons:
    apt:
        sources:
            - sourceline: 'ppa:masterminds/glide'
        packages:
            - glide

go:
    - 1.9.x
    - master

matrix:
    fast_finish: true
    allow_failures:
        - go: master

install:
    - ./travis/install.sh

script:
    - ./travis/test.sh
